# Generated by Django 5.1.2 on 2024-10-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCategory',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.category',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': ['name'], 'ordering': ['name'], 'permissions': ()},
        ),
    ]
