# Generated by Django 5.1.2 on 2024-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(db_comment='product_name', max_length=100),
        ),
    ]
